### ISSUE TITLE
No such file or directory error

### ISSUE THREAD

**Issue by mohamadfaraji98** [SERGGroup/EESConnector#5]
Hi, I want to run a simple EES code with python without any input list:
This is my EES code which I saved it in a EES file and opened manually via python:

x^2+y^3=77
sqrt(x/(y^2+1))=2
alpha+x=1.234 

Afterthat, I would like to get the answer of these equations with python. But when I ran the python code I encountered this eror.
I checked the directory mentioned below, and I noticed that the program created 'ees_output.dat' file, but removed it after a few second. Eventually, this error occured

Could you please help me to figure out and solve this issue?

```
from EESConnect import EESConnector
from tkinter import filedialog
import tkinter as tk

root = tk.Tk()
root.withdraw()
ees_file_path = filedialog.askopenfilename()


with EESConnector() as ees:
    ees.ees_file_path = ees_file_path
    result = ees.calculate([])
    print(result[1])


File ~\.conda\envs\EES\Lib\site-packages\EESConnect\EES_connect.py:217, in EESConnector.__read_output_file(filename)
    214 @staticmethod
    215 def __read_output_file(filename):
--> 217     with open(filename, "r") as f:
    219         lines = f.readlines()
    221     return_list = list()

[Errno 2] No such file or directory: 'C:\\Users\\Power 03\\.conda\\envs\\EES\\Lib\\site-packages\\EESConnect\\workspace\\ees_output.dat'


```

**Comment by pietroUngar** [comment]
hi Mohamad,

The fact is that you had to insert the line of code wich creates the file in **your EES code**. To do so you had to modify your file as follows:
```
$UnitSystem SI K kPa kJ 
$Import 'ees_input.dat' file$

x^2+y^3=77
sqrt(x/(y^2+1))=2
alpha+x=1.234

$Export file$ x y alpha
```

In the previous code there are three different parts:

### 1. Section wich imports the parameters from python:
```
$UnitSystem SI K kPa kJ 
$Import 'ees_input.dat' file$
```
After the _"$Import 'ees_input.dat' file$"_ section you can pass all the parameters that you would like to be provided by python. 
For example if you whant python to pass to your code the parameter "x" you can rewrite the code as follows:
```
$UnitSystem SI K kPa kJ 
$Import 'ees_input.dat' file$ x
```
Once you have defined here that 'x' should be provided by python you had to pass the value that you want to provide in the calculate statement in you python code. For example the following example can be used to set "10" as the value of "x" in the EES file
```python
from EESConnect import EESConnector
from tkinter import filedialog
import tkinter as tk

#select the ees file path
root = tk.Tk()
root.withdraw()
ees_file_path = filedialog.askopenfilename()

with EESConnector() as ees:
    
    ees.ees_file_path = ees_file_path
    result = ees.calculate([10])
    print(result[1])

```

Be carefull that in this way your system will be over-defines as writing "x" in the input line counts as an additional equation (it is equivalent of writing _"x = 10"_). 

The other thing to be noted is that if you try to run the code after the addition of the $import statement **it will not** work as EES will say that there's no "'ees_input.dat'" file (as that file will be generated by python). 

To test the file you can comment the $Import statement and manualy set the parameter that should be passed by python:
```
$UnitSystem SI K kPa kJ 
{$Import 'ees_input.dat' file$ x}
file$ = 'ees_output.dat'
x = 10
```
Be sure to delate the manual setting of the variables and uncomment the $Import statement before running it with python.

A final remart, as you've seen the first variable to be passed is this _'file$'_ string, this is because that is the way in wich python tell EES where to save the output of the calculation. **Hence be sure to include this name all the time as the first variable of the import statement**

### 2. Your code
```
x^2+y^3=77
sqrt(x/(y^2+1))=2
alpha+x=1.234
```
### 3. Section wich export the parameters
```
$Export file$ x y alpha
```
This section is needed to generate a file with the result that Python can read. All the variable listed after the '$Export file$' statement will be passed to python (in that order). This is the section that generate the "ees_output.dat" file so if you did not include it in the EES file the python code will trow the error that you're getting.

**Comment by mohamadfaraji98** [comment]
I really appreciate your prompt response. The problem was solved.
